"""initial schema

Revision ID: f5c99ffbd630
Revises: 
Create Date: 2026-06-27 03:39:16.619392
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f5c99ffbd630'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.Enum('tenant_admin', 'analyst', 'viewer', 'system', name='role_name'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('applicants',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_ref', name='uq_applicants_tenant_external_ref')
    )
    op.create_index(op.f('ix_applicants_created_at'), 'applicants', ['created_at'], unique=False)
    op.create_index(op.f('ix_applicants_email'), 'applicants', ['email'], unique=False)
    op.create_index(op.f('ix_applicants_external_ref'), 'applicants', ['external_ref'], unique=False)
    op.create_index(op.f('ix_applicants_tenant_id'), 'applicants', ['tenant_id'], unique=False)
    op.create_table('consent_notices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('purposes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', 'version', 'language', name='uq_consent_notice_version')
    )
    op.create_index(op.f('ix_consent_notices_created_at'), 'consent_notices', ['created_at'], unique=False)
    op.create_index(op.f('ix_consent_notices_is_active'), 'consent_notices', ['is_active'], unique=False)
    op.create_index(op.f('ix_consent_notices_jurisdiction'), 'consent_notices', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_consent_notices_key'), 'consent_notices', ['key'], unique=False)
    op.create_index(op.f('ix_consent_notices_language'), 'consent_notices', ['language'], unique=False)
    op.create_index(op.f('ix_consent_notices_tenant_id'), 'consent_notices', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('signing_secret', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_created_at'), 'webhook_endpoints', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_is_active'), 'webhook_endpoints', ['is_active'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_tenant_id'), 'webhook_endpoints', ['tenant_id'], unique=False)
    op.create_table('onboarding_cases',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('state', sa.Enum('created', 'consent_pending', 'documents_pending', 'verifying', 'in_review', 'approved', 'rejected', 'abandoned', name='case_state'), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('risk_severity', sa.Enum('low', 'medium', 'high', 'critical', name='risk_severity'), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_cases_applicant_id'), 'onboarding_cases', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_onboarding_cases_created_at'), 'onboarding_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_onboarding_cases_reference'), 'onboarding_cases', ['reference'], unique=False)
    op.create_index(op.f('ix_onboarding_cases_state'), 'onboarding_cases', ['state'], unique=False)
    op.create_index(op.f('ix_onboarding_cases_tenant_id'), 'onboarding_cases', ['tenant_id'], unique=False)
    op.create_table('tenant_api_keys',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_api_keys_created_at'), 'tenant_api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenant_api_keys_is_active'), 'tenant_api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenant_api_keys_prefix'), 'tenant_api_keys', ['prefix'], unique=True)
    op.create_index(op.f('ix_tenant_api_keys_tenant_id'), 'tenant_api_keys', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_user_roles_created_at'), 'user_roles', ['created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Enum('applicant', 'guardian', name='consent_type'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('notice_version', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('jurisdiction', sa.String(length=32), nullable=False),
    sa.Column('purposes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_relationship', sa.String(length=64), nullable=True),
    sa.Column('receipt_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['consent_notices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_hash')
    )
    op.create_index(op.f('ix_consent_records_applicant_id'), 'consent_records', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_consent_records_case_id'), 'consent_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_consent_records_created_at'), 'consent_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_consent_records_notice_id'), 'consent_records', ['notice_id'], unique=False)
    op.create_index(op.f('ix_consent_records_tenant_id'), 'consent_records', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('pan', 'aadhaar', 'passport', 'driving_license', 'voter_id', 'other', name='document_type'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'processed', 'failed', 'quarantined', name='document_status'), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('redacted_storage_key', sa.String(length=512), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('ocr_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_applicant_id'), 'documents', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_content_sha256'), 'documents', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('retention_requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Enum('requested', 'approved', 'completed', 'rejected', name='retention_request_state'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_requests_applicant_id'), 'retention_requests', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_retention_requests_case_id'), 'retention_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_retention_requests_created_at'), 'retention_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_retention_requests_state'), 'retention_requests', ['state'], unique=False)
    op.create_index(op.f('ix_retention_requests_tenant_id'), 'retention_requests', ['tenant_id'], unique=False)
    op.create_table('review_tasks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'assigned', 'approved', 'rejected', 'escalated', name='review_status'), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('auto_approve', 'manual_review', 'auto_reject', 'approved', 'rejected', name='decision_type'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_assigned_to_user_id'), 'review_tasks', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_case_id'), 'review_tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_created_at'), 'review_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_tasks_priority'), 'review_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_review_tasks_status'), 'review_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_review_tasks_tenant_id'), 'review_tasks', ['tenant_id'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('auto_approve', 'manual_review', 'auto_reject', 'approved', 'rejected', name='decision_type'), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='risk_severity'), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_by', sa.String(length=32), nullable=False),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_decisions_case_id'), 'risk_decisions', ['case_id'], unique=False)
    op.create_index(op.f('ix_risk_decisions_created_at'), 'risk_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_decisions_decision'), 'risk_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_risk_decisions_tenant_id'), 'risk_decisions', ['tenant_id'], unique=False)
    op.create_table('risk_signals',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='risk_severity'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_case_id'), 'risk_signals', ['case_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_code'), 'risk_signals', ['code'], unique=False)
    op.create_index(op.f('ix_risk_signals_created_at'), 'risk_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_signals_severity'), 'risk_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_signals_tenant_id'), 'risk_signals', ['tenant_id'], unique=False)
    op.create_table('verification_steps',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('step_type', sa.Enum('document_ocr', 'document_authenticity', 'pan_check', 'aadhaar_check', 'liveness', 'face_match', 'sanctions_screening', name='verification_step_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'dependency_not_configured', name='verification_step_status'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_steps_case_id'), 'verification_steps', ['case_id'], unique=False)
    op.create_index(op.f('ix_verification_steps_created_at'), 'verification_steps', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_steps_status'), 'verification_steps', ['status'], unique=False)
    op.create_index(op.f('ix_verification_steps_step_type'), 'verification_steps', ['step_type'], unique=False)
    op.create_index(op.f('ix_verification_steps_tenant_id'), 'verification_steps', ['tenant_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'failed', 'retrying', 'dead_letter', name='webhook_delivery_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['onboarding_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_case_id'), 'webhook_deliveries', ['case_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_created_at'), 'webhook_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_endpoint_id'), 'webhook_deliveries', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_idempotency_key'), 'webhook_deliveries', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_tenant_id'), 'webhook_deliveries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_tenant_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_idempotency_key'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_created_at'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_case_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_verification_steps_tenant_id'), table_name='verification_steps')
    op.drop_index(op.f('ix_verification_steps_step_type'), table_name='verification_steps')
    op.drop_index(op.f('ix_verification_steps_status'), table_name='verification_steps')
    op.drop_index(op.f('ix_verification_steps_created_at'), table_name='verification_steps')
    op.drop_index(op.f('ix_verification_steps_case_id'), table_name='verification_steps')
    op.drop_table('verification_steps')
    op.drop_index(op.f('ix_risk_signals_tenant_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_severity'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_created_at'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_code'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_case_id'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_risk_decisions_tenant_id'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_decision'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_created_at'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_case_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_review_tasks_tenant_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_status'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_priority'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_created_at'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_case_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_assigned_to_user_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_retention_requests_tenant_id'), table_name='retention_requests')
    op.drop_index(op.f('ix_retention_requests_state'), table_name='retention_requests')
    op.drop_index(op.f('ix_retention_requests_created_at'), table_name='retention_requests')
    op.drop_index(op.f('ix_retention_requests_case_id'), table_name='retention_requests')
    op.drop_index(op.f('ix_retention_requests_applicant_id'), table_name='retention_requests')
    op.drop_table('retention_requests')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_applicant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_consent_records_tenant_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_notice_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_created_at'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_case_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_applicant_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_user_roles_created_at'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tenant_api_keys_tenant_id'), table_name='tenant_api_keys')
    op.drop_index(op.f('ix_tenant_api_keys_prefix'), table_name='tenant_api_keys')
    op.drop_index(op.f('ix_tenant_api_keys_is_active'), table_name='tenant_api_keys')
    op.drop_index(op.f('ix_tenant_api_keys_created_at'), table_name='tenant_api_keys')
    op.drop_table('tenant_api_keys')
    op.drop_index(op.f('ix_onboarding_cases_tenant_id'), table_name='onboarding_cases')
    op.drop_index(op.f('ix_onboarding_cases_state'), table_name='onboarding_cases')
    op.drop_index(op.f('ix_onboarding_cases_reference'), table_name='onboarding_cases')
    op.drop_index(op.f('ix_onboarding_cases_created_at'), table_name='onboarding_cases')
    op.drop_index(op.f('ix_onboarding_cases_applicant_id'), table_name='onboarding_cases')
    op.drop_table('onboarding_cases')
    op.drop_index(op.f('ix_webhook_endpoints_tenant_id'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_is_active'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_created_at'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_consent_notices_tenant_id'), table_name='consent_notices')
    op.drop_index(op.f('ix_consent_notices_language'), table_name='consent_notices')
    op.drop_index(op.f('ix_consent_notices_key'), table_name='consent_notices')
    op.drop_index(op.f('ix_consent_notices_jurisdiction'), table_name='consent_notices')
    op.drop_index(op.f('ix_consent_notices_is_active'), table_name='consent_notices')
    op.drop_index(op.f('ix_consent_notices_created_at'), table_name='consent_notices')
    op.drop_table('consent_notices')
    op.drop_index(op.f('ix_applicants_tenant_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_external_ref'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_email'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_created_at'), table_name='applicants')
    op.drop_table('applicants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
